### ISSUE TITLE
User can search cards by Pokemon name

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/ajax-project#1]
## 💰 Motivation

User can search Pokemon by name

## 📐 Functionality

Create a responsive form that allows users enter Pokemon name in a search bar

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/90783131/171785194-78498ca6-d12a-4c0a-8159-ea7b26da4a50.png)
![image](https://user-images.githubusercontent.com/90783131/171785281-3fd7d74f-e510-4234-9f01-b76adaac9aa1.png)

## ✅ Task List

- [x] Create new html page skeleton
- [x] Link and Add CSS page
- [x] Style the page and remove unnecessary CSS
- [x] Make the input of the search `required`.
- [x] Add 3 cards to display on homepage
- [x] Add text below image to show name of card and value
- [x] Add heart for users to click on (functionality added later on)
- [x] Test the functions in a private browser
- [x] Fix any errors
